### PR TITLE
Handle API change between 2.0.2 and newer

### PR DESCRIPTION
**Pull request by Tenzer**
This looks better to me at least :)

### CODE REVIEW

**Comment by stephenyeargin** [comment]
:+1:

**Comment by stephenyeargin** [comment]
After this clears CI, I'll publish a new NPM version.

**Comment by Tenzer** [comment]
If you can hold on an hour or so I also have a PR for #7. It should be
working, but it will conflict with the change from this PR, so it was nicer
for me to get this out of the way first.

On Thursday, June 25, 2015, Stephen Yeargin <notifications@github.com>
wrote:

> Merged #11 <https://github.com/stephenyeargin/hubot-grafana/pull/11>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stephenyeargin/hubot-grafana/pull/11#event-340434428>.
>


-- 

--
Venlig hilsen / Kind regards
Jeppe Toustrup

**Comment by stephenyeargin** [comment]
Word, I can do that.

**Pull request merged**
