### PR TITLE
Ensure Hubot returns specified template value 

### LINKED ISSUE #28: Current Template Overriding Specified Template Value
Hi. I have a dashboard `monitoring-default`, with a single variable, `$server`. When asking hubot-grafana for a specific server's load, I use the following command: `graf db monitoring-default:load server=www-03.example.com now-1h`.

My expectation is that Hubot's response would begin with "www-03.example.com load: ", but instead a different (but valid) variable value is shown. This happens to be the same variable value that loads by default when the `monitoring-default` dashboard is loaded in a browser (the `current` value in the dashboard json).

I am unsure of the nuances and more general use-cases for templates with hubot-grafana, but have successfully been able to achieve the desired result here: https://github.com/criticalmass/hubot-grafana/commit/dfb408492449a17ce14f9234a8886815bdd504d7. If you find this approach acceptable, I can create a PR with the changes.

Cheers!

### PR DESCRIPTION
**Pull request by lanyonm**
Fixes #28. I separated the PR into two commits to show the failing test in the first and the fix in the second. I wasn't able to find much in the way of integration testing hubot scripts, but https://github.com/amussey/hubot-testing-boilerplate helped a great deal. Hopefully you don't find it to be too much overhead.

Let me know if I can provide any additional information.

Cheers,
Mike

### CODE REVIEW

**Comment by stephenyeargin** [comment]
:heart_eyes_cat: for getting Nock to work with this repo. I've been meaning to fight with it again for weeks (even copying @rick's work on `hubot-graphme`) It's badly needed on many of the other methods as well, so this will be a good start for that.

Code looks :+1:

/cc @Tenzer

**Comment by Tenzer** [comment]
I've never really figured out what the original problem was, but if you think it looks good @stephenyeargin, then go ahead and merge it.

**Comment by lanyonm** [comment]
@Tenzer,
This is the output of the test before the fix is applied:
```
      AssertionError: expected [ Array(2) ] to deeply equal [ Array(2) ]
      + expected - actual

           "hubot graf db monitoring-default:network server=ww3.example.com now-6h"
         ]
         [
           "hubot"
      -    "ww1.example.com network: http://play.grafana.org/render/dashboard-solo/db/monitoring-default/?panelId=7&width=1000&height=500&from=now-6h&to=now&var-server=ww3.example.com - http://play.grafana.org/dashboard/db/monitoring-default/?panelId=7&fullscreen&from=now-6h&to=now&var-server=ww3.example.com"
      +    "ww3.example.com network: http://play.grafana.org/render/dashboard-solo/db/monitoring-default/?panelId=7&width=1000&height=500&from=now-6h&to=now&var-server=ww3.example.com - http://play.grafana.org/dashboard/db/monitoring-default/?panelId=7&fullscreen&from=now-6h&to=now&var-server=ww3.example.com"
         ]
       ]
```
Hopefully this illustrates the problem clearly.

**Comment by Tenzer** [comment]
Ah, that explains it a lot more. I thought it was getting the wrong graph or something, but I didn't think of looking at the title of the graph!

**Comment by stephenyeargin** [comment]
Released with `v1.4.6`

**Pull request merged**
